name: invite_friends
description: A polished, responsive Flutter implementation of an invite screen.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter
  pretty_qr_code: ^3.6.0
  share_plus: ^13.3.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
